Distributions with deleted nonsence values and with cuts based on phy…
CBM-ML/correlations pull request #1
Opened 2021-04-07 15:04 UTC by conformist89

…sical processes or detector geometry

2021-04-07 15:59 UTC, viktorklochkov commented
Hi @conformist89! Usually, .pdf and .docx files are not stored in git, maybe you could remove them and leave only code.

2021-04-07 16:04 UTC, viktorklochkov commented
Also, is there a way to move code to .py file? In .ipynb there are also output cells

2021-04-07 16:46 UTC, shahidzk1 commented
> Also, is there a way to move code to .py file? In .ipynb there are also output cells

We can store an .ipynb file without the output, save just the raw file and upload it. I am working on creating a .py file

2021-04-08 08:52 UTC, viktorklochkov approved these changes

2021-04-08 10:30 UTC, viktorklochkov commented
@shahidzk1, please approve the changes if they are fine and we can merge it

2021-04-08 10:44 UTC, shahidzk1 commented
@conformist89 the concurrent package was used in the tree_importer package to import in stuff. if you aren't using it in the rest of the code then try to remove it. i have suggested this change.

2021-04-08 10:52 UTC, shahidzk1 commented on quality_cuts/new_var_dist.py
> +from concurrent.futures import ThreadPoolExecutor
remove these

2021-04-08 10:55 UTC, shahidzk1 requested changes

2021-04-08 10:55 UTC, shahidzk1 commented on quality_cuts/new_var_dist.py
> +file = tree_importer('/home/olha/CBM/dataset/10k_events_PFSimplePlainTree.root',
change file to df_original, it is already a dataframe

2021-04-08 10:55 UTC, shahidzk1 commented on quality_cuts/new_var_dist.py
> +executor = ThreadPoolExecutor(8)
remove these if you don't use them, they are already included in the tree_importer file

2021-04-08 10:55 UTC, shahidzk1 commented on quality_cuts/new_var_dist.py
> +
make a function and save it in a separate python file as quality_cuts. The other cuts will be named as pre-selection cuts

2021-04-08 12:44 UTC, shahidzk1 approved these changes
Olga try to write also in English what the code is doing. In the future you will remember why did you write this code the way it is and also others can read it as well. I also don't elaborate my code but that is generally a bad practice.

2021-04-08 12:50 UTC, shahidzk1 commented
@viktorklochkov this work should be saved in data cleaning, correlations one is a different work. We should create another repository for it. One for correlations and one for data cleaning and pre-processing.

2021-04-08 13:30 UTC, conformist89 commented
> .

I added comments

2021-04-08 16:16 UTC, shahidzk1 approved these changes

2021-04-08 16:18 UTC, shahidzk1 approved these changes

2021-04-08 18:47 UTC, merged